config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :contacts, only: [ :new, :create ]
  resources :projects
  get '/savecv', to: 'pages#savecv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord


end

app/models/project.rb
class Project < ApplicationRecord
  has_many :projectfeatures, dependent: :destroy, foreign_key: true
end

app/models/projectfeature.rb
class Projectfeature < ApplicationRecord
  belongs_to :project
end

app/models/techno.rb
class Techno < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/workexperience.rb
class Workexperience < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_filter :redirect_to_https

  # def redirect_to_https
  #   redirect_to :protocol => "https://" unless (request.ssl? || request.local?)
  # end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)

  end

  private

  def contact_params
    params.require(:contact).permit(:firstname, :name, :email, :company, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
    @projects = Project.all
    @workexperiences = Workexperience.all
  end

  def savecv
    # filepath = "CV.pdf"
    # @file = File.read(filepath)
    send_file 'app/assets/data/CV.pdf', type: "application/pdf"
  end
end

app/controllers/projectfeatures_controller.rb
class ProjectfeaturesController < ApplicationController
  before_action :authenticate_user!

  def index
    @projectfeatures = Projectfeature.all
  end

  def show
    @projectfeatures = Projectfeature.find(params[:id])
  end

  def new
    @projectfeatures = Projectfeature.new
  end

  def create
    @projectfeatures_new = Projectfeature.new(projectfeatures_params)
    @projectfeatures_new.save
    redirect_to projectfeatures_path(@projectfeatures_new)
  end

  def edit
    @projectfeatures = Projectfeature.find(params[:id])
  end

  def update
    @projectfeatures = Projectfeature.find(params[:id])
    @projectfeatures.update(projectfeatures_params)
    redirect_to projectfeatures_path(@projectfeatures)
  end

  def destroy
    @projectfeatures = Projectfeature.find(params[:id])
    @projectfeatures.destroy
    redirect_to projectfeatures_main_path
  end

  private

  def projectfeatures_params
    params.require(:projectfeatures).permit(:projectfeaturesname, :context, :codetags, { features: [] })
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project_new = Project.new(project_params)
    @project_new.save
    redirect_to projects_path(@project_new)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_main_path
  end

  private

  def project_params
    params.require(:project).permit(:projectname, :context, :codetags, { features: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_new.html.erb
<%= simple_form_for (@contact) do |f| %>
  <div class="form-check-inlin">
    <%= f.input :firstname, as: :string, class:"input-type" %>
    <%= f.input :name, as: :string, class:"input-type" %>
  </div>
  <div class="form-check-inlin">
    <%= f.input :email, as: :string, class:"input-type" %>
    <%= f.input :company, as: :string, class:"input-type" %>
  </div>
  <%= f.input :message, as: :text, class:"input-type" %>
  <%= f.button :submit, class: "primary-button", value: "Valider ma demande"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio Tristan Monteiro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%# <link rel="stylesheet" href="devicon.min.css"> %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="text-sm sm:text-base">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_experience.html.erb
<h2 class="text-center md:text-3xl"  id="formation"><span class="gradient-text">02. </span>Mes formations</h2>
<p class="text-center w-full lg:w-1/2 mx-auto pb-5">Ingénieur de formation, j'ai trouvé mon côté tech dans le digital dans un premier temps (APIs, Automatisation, Scraping), avant de découvrir le développement d'applications web au wagon en 2021.</p>
<div class="flex flex-col md:grid grid-cols-9 mx-auto p-2 text-blue-50 section">
  <!-- left -->
  <div class="flex flex-row-reverse md:contents">
    <div
      class="greyblue-bg w-500 col-start-1 col-end-5 p-4 rounded-xl my-4 ml-auto shadow-md">
      <h3 class="font-semibold text-lg mb-1 pb-3 text-center">Cycle préparatoire intégrée <> EBI (2015-2017)</h3>
      <ul class="list-colored">
        <li class="leading-tight text-justify">Maths & Programmation : Algorithmie en C+, analyse statistique en R</li>
        <li class="leading-tight text-justify">Physique, Chimie, Biologie</li>
      </ul>
    </div>
    <div class="col-start-5 col-end-6 md:mx-auto relative mr-10">
      <div class="h-full w-6 flex items-center justify-center">
        <div class="h-full w-1 bg-white pointer-events-none"></div>
      </div>
      <div
        class="w-6 h-6 absolute top-1/2 -mt-3 rounded-full bg-white w-500 shadow"
      ></div>
    </div>
  </div>
  <!-- right -->
  <div class="flex md:contents">
    <div class="col-start-5 col-end-6 mr-10 md:mx-auto relative">
      <div class="h-full w-6 flex items-center justify-center">
        <div class="h-full w-1 bg-white pointer-events-none"></div>
      </div>
      <div
        class="w-6 h-6 absolute top-1/2 -mt-3 rounded-full bg-white w-500 shadow"
      ></div>
    </div>
    <div class="greyblue-bg w-500 col-start-6 col-end-10 p-4 rounded-xl my-4 mr-auto shadow-md">
      <h3 class="font-semibold text-lg mb-1 pb-3 text-center">Cycle ingénieur <> EBI (2017-2020)</h3>
      <ul class="list-colored">
        <li class="leading-tight text-justify"> Lancement de produit, stratégie digitale</li>
        <li class="leading-tight text-justify">Projets scientifiques d'innovation : Sel de déneigement écologique, présenté au MEDEF Paris, puis à 2 concours d'innovation dont Innov'street</li>
      </ul>
    </div>
  </div>
  <!-- left -->
    <div class="flex flex-row-reverse md:contents">
      <div class="greyblue-bg w-500 col-start-1 col-end-5 p-4 rounded-xl my-4 ml-auto shadow-md">
        <h3 class="font-semibold text-lg mb-1 pb-3 text-center">Stage Consultant Digital <> Cartelis (2020)</h3>
        <ul class="list-colored">
          <li class="leading-tight text-justify">Mission client <> Fluow : Accompagnement dans la mise en place d'un système de prospection automatisée</li>
          <li class="leading-tight text-justify">Construction de ressources : Plan de tracking Web Firebase, planning digital</li>
          <li class="leading-tight text-justify">Actions marketing (Rédaction d'articles data, scénario automation )</li>
        </ul>
      </div>
      <div class="col-start-5 col-end-6 md:mx-auto relative mr-10">
        <div class="h-full w-6 flex items-center justify-center">
          <div class="h-full w-1 bg-white pointer-events-none"></div>
        </div>
        <div class="w-6 h-6 absolute top-1/2 -mt-3 rounded-full bg-white w-500 shadow"></div>
      </div>
  </div>
  <div class="flex md:contents">
    <div class="col-start-5 col-end-6 mr-10 md:mx-auto relative">
      <div class="h-full w-6 flex items-center justify-center">
        <div class="h-full w-1 bg-white pointer-events-none"></div>
      </div>
      <div
        class="w-6 h-6 absolute top-1/2 -mt-3 rounded-full bg-white w-500 shadow"
      ></div>
    </div>
    <div class="greyblue-bg w-500 col-start-6 col-end-10 p-4 rounded-xl my-4 mr-auto shadow-md">
      <h3 class="font-semibold text-lg mb-1 pb-3 text-center">Bootcamp Développeur Web <> Le wagon (2021)</h3>
      <ul class="list-colored">
        <li class="leading-tight text-justify">9 semaines de cours intensifs de code pour apprendre HTML, CSS, Bootstrap, JavaScript ES6,
                                              SQL, git, GitHub, Heroku et Ruby on Rails.</li>
        <li class="leading-tight text-justify">Conception, implémentation et mise en production d'un production un clone de AirBnB</li>
      </ul>
    </div>
  </div>
  <!-- end -->
</div>

app/views/pages/_oldcard.html.erb
<div class="slider">

	<div class="slide-track">
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png" height="100" width="250" alt="" />
		</div>
	</div>

</div>

app/views/pages/_other.html.erb
<div class="background-sombre section" id="realisations">
  <%# Services proposées %>
  <div class="container" id="service">
    <h2 class="mb-5">Mes services</h2>
    <div class="container-skill">
    <p class="text-center mb-5">Je vous aiderai pour la mise en place de votre MVP sur Rails, ou pour améliorer votre produit existant, développer des nouvelles fonctionnalités, intégrations. Voici les services que je propose : </p>
      <div class="blocs-service">
        <div class="bloc-service">
          <img src=<%= image_path("frontend.svg")%> alt="frontend" class="skill-desc-photo">
          <div class="bloc-service-title">
            <h3 class="titleblack gradient-text py-2">Front-end</h3>
          </div>
          <div class="skills-wrapper">
            <ul class="fa-ul">
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Création de site vitrine pour votre entreprise</li>
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Mise en place du design front-end à partir de vos maquettes</li>
            </ul>
          </div>
        </div>
        <div class="bloc-service">
        <img src=<%= image_path("backend.svg")%> alt="frontend" class="skill-desc-photo">
          <div class="bloc-service-title">
            <h3 class="title-black gradient-text py-2">Back-end</h3>
          </div>
          <div class="skills-wrapper">
            <ul class="fa-ul">
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Développement de nouvelles fonctionnalités sur votre application RoR</li>
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Intégration de services tiers à votre application RoR</li>
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Création de MVP pour votre entreprise</li>
            </ul>
          </div>
        </div>
        <div class="bloc-service">
          <div class="bloc-service-title">
            <h3 class="titleblack gradient-text py-2">Production</h3>
          </div>
          <div class="skills-wrapper">
             <ul class="fa-ul">
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Mise en production de mon travail </li>
              <li class="py-3"><span class="fa-li"><i class="fas fa-check green"></i></span>
              Résolution des bugs sur Heroku </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section-logo section" id="banner-company">
  <h2 class="white pb-5">Ils me font confiance</h2>
  <div class="slider">
    <div class="slide-track">
      <div class="slide"><img src=<%= image_path("logo-mediapp.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-cartelis.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-goodwill.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-bien-fonde.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-mister-auto.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-mediapp.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-cartelis.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-goodwill.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-bien-fonde.png")%> class="logo-company" /></div>
      <div class="slide"><img src=<%= image_path("logo-mister-auto.png")%> class="logo-company" /></div>
    </div>
  </div>
</div>

app/views/pages/_projectcardfree.html.erb
<%= link_to project_path(project),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-window-#{project.id}", class: 'card pulse'} do %>
  <div class="card__head">
    <div class="card__image">
      <%= image_tag project.imgurl, { :class=>"ui-button-text button_text" } %>
    </div>
    <div class="card__author">
      <div class="author">
        <img src="https://s.gravatar.com/avatar/7ff9e93ff25e002bc49f4d69c0c3eac7?s=80" alt="Author of Tobias Reich" class="author__image">
        <div class="author__content">
          <p class="author__header"> <%= project.projectname %></p>
          <p class="author__subheader">Goodwill</p>
        </div>
      </div>
    </div>
  </div>
  <div class="card__body">
    <h3 class="card__headline"><%= project.projectname %></h3>
    <p class="card__text"><%= project.context %></p>
  </div>
  <div class="card__foot">
    <span class="card__link">En savoir plus</span>
  </div>
  <div class="card__border"></div>
<% end %>

app/views/pages/home.html.erb
<!-- 111 Navbar -->
<div id="navbar">
  <img src=<%= image_path("logo.png")%> alt="photo" class="banner-logo">
  <div class="flex justify-center">
    <a href="#formation" class="nav-category invisible w-0 md:visible md:w-auto">Formation</a>
    <a href="#experience" class="nav-category invisible w-0 md:visible md:w-auto">Experience pro</a>
    <a href="#project" class="nav-category invisible w-0 md:visible md:w-auto">Projets</a>
    <%= link_to "Télécharger mon CV", savecv_path, class:"cta-red nav-category" %>
  </div>
</div>

<div class="flex items-center banner items">
  <div class="block m-auto md:flex section justify-around leading-9 md:leading-loose items-center text-center md:text-left">
    <img src=<%= image_path("undraw-banner.svg")%> alt="photo" class="w-36 mx-auto md:w-1/3 text-center mt-5 visible md:invisible md:w-0 pb-5">
    <div class="w-full md:w-1/2">
      <p class="gradient-text mb-5 text-xl">Salut, je suis </p>
      <h1 class="text-6xl font-bold mb-5">Tristan Monteiro</h1>
      <h3 class="mb-10">Ingénieur / développeur Ruby on Rails</h3>
      <a href="#apropos" class="cta-red">En découvrir plus !</a>
    </div>
    <img src=<%= image_path("undraw-banner.svg")%> alt="photo" class="w-36 mx-auto md:w-1/3 text-center mt-5 invisible md:visible">
  </div>
</div>

<h2 class="text-center md:text-3xl" id="apropos"><span class="gradient-text">01. </span>A propos de moi</h2>
<div class="block md:flex section justify-evenly items-center">
  <div class="h-4/6 flex relative justify-center">
    <img src=<%= image_path("tristan-pro.png")%> alt="photo" class="w-64 h-64 rounded border-double border-4 border-sky-500">
    <div class="w-64 h-64 rounded border-double border-4 border-whiteimage-apropos absolute top-4 right-4 invisible md:visible"></div>
  </div>
  <div class="text-center md:text-left w-full md:w-1/3 mt-5 md:mt-0">
    <p class="pb-3">Après des études d'ingénieur, j'ai accompagné pendant 2 ans des jeunes start-ups à développer leurs processus commerciaux et digitaux (SEO, Automation, Scraping, automatisation de process). </p>
    <p class="pb-3">Après ma formation au wagon, j'ai continué de me former sur rails, et Javascript à travers des formations, projets persos, et lectures de documentations / articles. </p>
    <p class="pb-3">Ayant finalisé mes dernières missions freelances en Octobre 2022, je cherche aujourd'hui à intégrer une start-up en croissance en tant que développeur Junior fullstack/backend. Je recherche une équipe bienveillante, qui travaille bien et vite, respectueuse des bonnes pratiques du code</p>
  </div>
</div>

<%= render "experience" %>

<%# Mes technologies %>
<h2 class="pb-4 text-center md:text-3xl"><span class="gradient-text">03. </span>Mes technologies</h2>
<div class="section" id="techno">
  <div class="relative h-80 md:h-48">
    <div class="technos-wrapper py-2">
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg" class="logo-tech skill w-14 md:w-18 m-4"/>
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-plain-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-plain-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-plain-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original-wordmark.svg" class="logo-tech skill w-14 md:w-18 m-4" />
    </div>
  </div>
</div>


<h2 class="text-center md:text-3xl" id="experience"><span class="gradient-text">04. </span>Mes expériences pro</h2>
<div class="rounded w-full lg:w-4/5 xl:w-2/3 mx-auto mt-4 block lg:flex section justify-evenly" data-controller="tabdisplay">
<% first_id =  @workexperiences.first.id %>
  <ul id="tabs" class="py-2 px-1 mb-8 w-full md:w-1/5 flex md:inline overflow-x-auto md:overflow-auto">
  <%= %>
    <% @workexperiences.each do |exp| %>
        <% if exp.id == first_id  %>
          <li class="gradient-text min-w-fit px-4 font-bold py-1 text-base md:py-2 border-gradient rounded-t-mb-px border-gradient">
            <a id="default-tab" href="#<%= exp.clientname %>"><%= exp.clientname %></a>
          </li>
          <% else %>
          <li class="px-4 font-light min-w-fit py-1 md:py-2 white-tab">
            <a id="default-tab" href="#<%= exp.clientname %>"><%= exp.clientname %></a>
          </li>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="tab-contents" class="w-full md:2/3">
    <% @workexperiences.each do |exp| %>
      <% if exp.id == first_id %>
        <div class="md:p-4" id="<%= exp.clientname %>">
      <% else  %>
        <div class="md:p-4 hidden" id="<%= exp.clientname %>">
      <% end %>
          <p><%= exp.interval %></p>
          <p class="gradient-text bold pb-3 md:pb-0"><%= exp.role %></p>
          <p class="pb-5"><%= exp.description %></p>
          <hr/>
          <ul class="list-colored">
            <% exp.feature.each do |feature| %>
              <li><%= feature %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    </div>
  </div>
</div>


<div id="project" class="section">
<h2 class="text-center md:text-3xl"><span class="gradient-text">05. </span>Mes projets</h2>
  <div class="project-cards">
    <% @projects.each_with_index do |project, index| %>
      <div class="block lg:flex items-center justify-evenly mb-5 lg:mb-0">
        <%= image_tag project.imgurl, { :class=>"w-full md:w-1/2 lg:w-0 lg:hidden mx-auto lg:mx-0 text-center mt-5 px-3 md:px-0 visible lg:invisible lg:h-0 bshadow" } %>
        <% if index.even? %>
          <%= image_tag project.imgurl, { :class=>"w-0 md:w-full mx-auto lg:mx-0 text-center md:w-1/2 lg:w-1/3 mt-5 px-3 md:px-0 invisible lg:visible h-0 lg:h-auto bshadow" } %>
        <% end  %>
        <div class="project-card block lg:flex justify-evenly items-center pb-5 mt-4 md:mt-16 w-full lg:w-1/3">
          <div class="block desc-content">
            <div class="flex justify-between">
              <h3 class ="text-center md:text-left"><%= project.projectname %></h3>
              <div class="flex">
                <% if project.githublink.length != 0 %>
                  <a class="ml-7" href =<% project.githublink  %>>
                    <img src=<%= image_path("github-logo.png")%> alt="photo" class="w-8">
                  </a>
                <% end %>
                <% if project.weblink.length != 0 %>
                  <a class="ml-7" href =<% project.weblink  %>>
                    <img src=<%= image_path("logo-internet.png")%> alt="photo" class="w-8">
                  </a>
                <% end %>
              </div>
            </div>
            <div class="greyblue-bg my-7 p-3 rounded-xs">
              <p><%= project.context %></p>
            </div>
            <p><%= project.projecttype %></p>
            <ul class="list-colored pb-5">
              <% project.features.each do |feature| %>
                <li class="px-5"><%= feature .tr(',', ' ')%></li>
              <% end %>
            </ul>
            <hr/>
            <ul class="flex justify-evenly">
              <% project.codetags.each do |tag| %>
                <li class="px-5 text-xs font-bold"><%= tag .tr(',', ' ')%></li>
              <% end %>
            </ul>
          </div>
        </div>
        <% if index.odd? %>
          <%= image_tag project.imgurl, { :class=>"w-full mx-auto lg:mx-0 text-center md:w-1/2 lg:w-1/3 mt-5 px-3 md:px-0 invisible lg:visible h-0 lg:h-auto bshadow" } %>
        <% end  %>
      </div>
    <% end %>
  </div>
</div>

<%# Div Client %>
<h2 class="text-center md:text-3xl">Mes clients en parlent</h2>
<div class="block md:flex max-w-md mx-auto md:max-w-2xl mt-6 min-w-0 break-words w-full mb-12 shadow-lg mt-16 justify-between">
    <div class="px-6 mx-3 my-5 md:my-0 bg-white rounded-xl">
        <div class="text-center mt-2">
            <h3 class="text-2xl text-slate-700 font-bold leading-normal mb-1">Alizée</h3>
            <div class="text-xs mt-0 mb-2 text-slate-400 font-bold uppercase">
                <i class="fas fa-map-marker-alt mr-2 text-slate-400 opacity-75"></i>CEO Agence Bien-fondé
            </div>
        </div>
        <div class="mt-6 py-6 border-t border-slate-200 text-center">
            <div class="flex flex-wrap justify-center">
                <div class="w-full px-4">
                    <p class="font-light leading-relaxed text-slate-600 mb-4">" Tristan a réalisé un travail de précision et plus poussé que ce qui était demandé. Il a su opérer un suivi au quotidien et donner ses inputs lorsque cela lui était demandé. Je le recommande vivement"</p>
                </div>
            </div>
        </div>
    </div>
    <div class="px-6 mx-3 bg-white rounded-xl">
        <div class="text-center mt-2">
            <h3 class="text-2xl text-slate-700 font-bold leading-normal mb-1">Guillaume</h3>
            <div class="text-xs mt-0 mb-2 text-slate-400 font-bold uppercase">
                <i class="fas fa-map-marker-alt mr-2 text-slate-400 opacity-75"></i>CEO Mediapp
            </div>
        </div>
        <div class="mt-6 py-6 border-t border-slate-200 text-center">
            <div class="flex flex-wrap justify-center">
                <div class="w-full px-4">
                    <p class="font-light leading-relaxed text-slate-600 mb-4">" Tristan est très à l'écoute, réactif, efficace, disponible, force de proposition : c'était un vrai plaisir de collaborer avec lui, je le recommande vivement !"</p>
                </div>
            </div>
        </div>
    </div>
</div>


<%# Footer %>
<div class="footer mt-5">
  <div class="footer-links">
    <a href="https://github.com/Git-TM"><img src=<%= image_path("github-logo.png")%> alt="photo" class="w-6"></a>
    <a href="https://www.linkedin.com/in/tristan-monteiro/">
      <svg
        class="w-6 h-6 text-white-500 fill-current"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 448 512">
        <path
          d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"
        ></path>
      </svg>
    </a>
  </div>
  <div class="footer-copyright">
    <p>Tristan Monteiro, 2022 Paris</p>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <%= simple_form_for @project do |f| %>
    <%= f.input :projectname %>
    <%= f.input :context %>
    <%= f.button :submit %>
    <%= f.check_box :features, { :multiple => true }, 'foo', nil  %>
    <%= f.check_box :features, { :multiple => true }, 'foo', nil  %>
    <%= f.check_box :features, { :multiple => true }, 'foo', nil  %>
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="admin-project-cards">
  <% @projects.each do |project| %>
  <div class="admin-project-card">
    <%= link_to project.projectname, project_path(project) %>
  </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= image_tag(@project.imgurl, alt: "logo", class: "admin-project-image") %>

<h1><%= @project.projectname %></h1>
<%= link_to "Editer", edit_project_path(@project) %>
<%= @project.context %>
</br>
<% @project.features.each do |tag| %>
  <%= tag %>
<% end %>
</br>
<%= @project.category %>
</br>
<%= @project.projecttype %>
</br>
<%= @project.features %>